feat : 베이직 버튼 컴포넌트 구현
TeamCrazyPerformance/TCP-Agenda pull request #45
Opened 2023-03-25 11:19 UTC by Astin01

버튼 컴포넌트 구현 코드입니다.

2023-03-26 06:08 UTC, usageness requested changes
고생하셨습니다! 몇 가지 궁금한 점이 있는데,

1. 컴포넌트 파일 경로를 `component/Basic/button` 으로 button과 input으로 나누어 둔 이유가 있을까요?

2. 린트/프리티어 적용이 안되고 있는 것 같은데, 이건 한 번 확인해보시고 안되면 평일에 만나서 같이 살펴봐요~

3. 이슈 당 PR은 하나로 매칭해주세요! 지금은 이슈 하나에 PR이 두 개씩 물려있는 모양이네요. 그리고 되도록이면 이슈에도 현재 개발중인 내용에 대해 적어주시면 좋습니다.

4. 다른분이 올리신 PR을 보시면 Closed 태그가 붙어있는게 있는데, 이걸 이슈번호에 물려주면 PR이 머지될때 이슈도 자동으로 close 상태로 변합니다! 한 번 적용해보세요~~ 

다른 세부적인 부분은 리뷰 내용 확인 부탁드려요 😄

2023-03-26 06:08 UTC, usageness commented on frontend/src/components/Basic/button.scss
> +    font-size: 16px;
변할 수 있는 요소의 사이즈 단위는 반응형 지원을 위해 px보다는 rem 단위를 사용합시다!

2023-03-26 06:08 UTC, usageness commented on frontend/src/components/Basic/button.scss
> +    border-bottom-left-radius: 4px;
이 부분은 아래처럼 간단히 쓸 수 있겠네요!

```css
border-radius: 4px;
```

2023-03-26 06:08 UTC, usageness commented on frontend/src/components/Basic/button.tsx
> +function Button() {
여기서 만든 버튼의 경우 다양하게 활용이 가능한 베이직 태그인데,
빈 태그만 있는 컴포넌트면 여러곳에서 가져와서 사용하기 어려울 것 같아요.
`children` 을 사용해서 자식 요소들을 받을 수 있도록 해봅시다!

2023-03-29 03:34 UTC, Astin01 commented
베이직 버튼 컴포넌트( 버튼 요소를 만들때 바탕이 되는 요소) 완성

2023-03-29 03:34 UTC, merged