feat : 베이직 인풋 컴포넌트 구현
TeamCrazyPerformance/TCP-Agenda pull request #46
Opened 2023-03-25 11:21 UTC by Astin01

베이직 인풋 컴포넌트 코드입니다.

2023-03-26 06:35 UTC, usageness requested changes
본 PR 이외의 리뷰 내용은 Button PR을 참고해주세요!

2023-03-26 06:35 UTC, usageness commented on frontend/src/components/Basic/input.scss
> +  background: $WHITE_000;
이전 PR인 Button 컴포넌트에서는 `background-color` 였던것 같은데,
하나로 통일해서 사용하는건 어떨까요?

2023-03-26 06:35 UTC, usageness commented on frontend/src/components/Basic/input.scss
> +  resize: none;
input 태그는 기본적으로 resize가 none입니다!
없어도 될 것 같은 속성이네요~

2023-03-26 06:35 UTC, usageness commented on frontend/src/components/Basic/input.tsx
> +}
Basic 컴포넌트들은 활용성을 위해 만드는 컴포넌트이기 때문에,
placeholder 등 기본 속성들은 자유롭게 사용할 수 있도록 해주시는게 좋을 것 같아요.
기타 모든 속성들을 인자로 받을 수 있게 부탁드릴게요!

2023-03-29 03:32 UTC, Astin01 commented
베이지 인풋  컴포넌트 완성
- 인풋 요소들을 만들때 쓰이는 기본 요소

2023-03-29 03:33 UTC, merged